# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blinky.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='blinky.proto',
  package='blinky',
  syntax='proto3',
  serialized_pb=_b('\n\x0c\x62linky.proto\x12\x06\x62linky\"G\n\rSetLEDRequest\x12\x0b\n\x03Red\x18\x01 \x01(\x05\x12\r\n\x05Green\x18\x02 \x01(\x05\x12\x0c\n\x04\x42lue\x18\x03 \x01(\x05\x12\x0c\n\x04LEDs\x18\x04 \x03(\x05\"\x1e\n\x0eSetLEDResponse\x12\x0c\n\x04LEDs\x18\x04 \x03(\x05\"\x1d\n\rGetLEDRequest\x12\x0c\n\x04LEDs\x18\x01 \x03(\x05\"B\n\tLEDStatus\x12\x0b\n\x03LED\x18\x01 \x01(\x05\x12\x0b\n\x03Red\x18\x02 \x01(\x05\x12\r\n\x05Green\x18\x03 \x01(\x05\x12\x0c\n\x04\x42lue\x18\x04 \x01(\x05\"3\n\x0eGetLEDResponse\x12!\n\x06Status\x18\x01 \x03(\x0b\x32\x11.blinky.LEDStatus2\x80\x01\n\x06\x42linky\x12:\n\x07SetLEDs\x12\x15.blinky.SetLEDRequest\x1a\x16.blinky.SetLEDResponse\"\x00\x12:\n\x07GetLEDs\x12\x15.blinky.GetLEDRequest\x1a\x16.blinky.GetLEDResponse\"\x00\x42,Z*github.com/vatine/blinky/client/pkg/protosb\x06proto3')
)




_SETLEDREQUEST = _descriptor.Descriptor(
  name='SetLEDRequest',
  full_name='blinky.SetLEDRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Red', full_name='blinky.SetLEDRequest.Red', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Green', full_name='blinky.SetLEDRequest.Green', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Blue', full_name='blinky.SetLEDRequest.Blue', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='LEDs', full_name='blinky.SetLEDRequest.LEDs', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=95,
)


_SETLEDRESPONSE = _descriptor.Descriptor(
  name='SetLEDResponse',
  full_name='blinky.SetLEDResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='LEDs', full_name='blinky.SetLEDResponse.LEDs', index=0,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=127,
)


_GETLEDREQUEST = _descriptor.Descriptor(
  name='GetLEDRequest',
  full_name='blinky.GetLEDRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='LEDs', full_name='blinky.GetLEDRequest.LEDs', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=158,
)


_LEDSTATUS = _descriptor.Descriptor(
  name='LEDStatus',
  full_name='blinky.LEDStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='LED', full_name='blinky.LEDStatus.LED', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Red', full_name='blinky.LEDStatus.Red', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Green', full_name='blinky.LEDStatus.Green', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Blue', full_name='blinky.LEDStatus.Blue', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=226,
)


_GETLEDRESPONSE = _descriptor.Descriptor(
  name='GetLEDResponse',
  full_name='blinky.GetLEDResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Status', full_name='blinky.GetLEDResponse.Status', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=228,
  serialized_end=279,
)

_GETLEDRESPONSE.fields_by_name['Status'].message_type = _LEDSTATUS
DESCRIPTOR.message_types_by_name['SetLEDRequest'] = _SETLEDREQUEST
DESCRIPTOR.message_types_by_name['SetLEDResponse'] = _SETLEDRESPONSE
DESCRIPTOR.message_types_by_name['GetLEDRequest'] = _GETLEDREQUEST
DESCRIPTOR.message_types_by_name['LEDStatus'] = _LEDSTATUS
DESCRIPTOR.message_types_by_name['GetLEDResponse'] = _GETLEDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SetLEDRequest = _reflection.GeneratedProtocolMessageType('SetLEDRequest', (_message.Message,), dict(
  DESCRIPTOR = _SETLEDREQUEST,
  __module__ = 'blinky_pb2'
  # @@protoc_insertion_point(class_scope:blinky.SetLEDRequest)
  ))
_sym_db.RegisterMessage(SetLEDRequest)

SetLEDResponse = _reflection.GeneratedProtocolMessageType('SetLEDResponse', (_message.Message,), dict(
  DESCRIPTOR = _SETLEDRESPONSE,
  __module__ = 'blinky_pb2'
  # @@protoc_insertion_point(class_scope:blinky.SetLEDResponse)
  ))
_sym_db.RegisterMessage(SetLEDResponse)

GetLEDRequest = _reflection.GeneratedProtocolMessageType('GetLEDRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETLEDREQUEST,
  __module__ = 'blinky_pb2'
  # @@protoc_insertion_point(class_scope:blinky.GetLEDRequest)
  ))
_sym_db.RegisterMessage(GetLEDRequest)

LEDStatus = _reflection.GeneratedProtocolMessageType('LEDStatus', (_message.Message,), dict(
  DESCRIPTOR = _LEDSTATUS,
  __module__ = 'blinky_pb2'
  # @@protoc_insertion_point(class_scope:blinky.LEDStatus)
  ))
_sym_db.RegisterMessage(LEDStatus)

GetLEDResponse = _reflection.GeneratedProtocolMessageType('GetLEDResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETLEDRESPONSE,
  __module__ = 'blinky_pb2'
  # @@protoc_insertion_point(class_scope:blinky.GetLEDResponse)
  ))
_sym_db.RegisterMessage(GetLEDResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z*github.com/vatine/blinky/client/pkg/protos'))

_BLINKY = _descriptor.ServiceDescriptor(
  name='Blinky',
  full_name='blinky.Blinky',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=282,
  serialized_end=410,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetLEDs',
    full_name='blinky.Blinky.SetLEDs',
    index=0,
    containing_service=None,
    input_type=_SETLEDREQUEST,
    output_type=_SETLEDRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetLEDs',
    full_name='blinky.Blinky.GetLEDs',
    index=1,
    containing_service=None,
    input_type=_GETLEDREQUEST,
    output_type=_GETLEDRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BLINKY)

DESCRIPTOR.services_by_name['Blinky'] = _BLINKY

# @@protoc_insertion_point(module_scope)
