// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.4
// source: blinky.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetLEDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Red   int32   `protobuf:"varint,1,opt,name=Red,proto3" json:"Red,omitempty"`
	Green int32   `protobuf:"varint,2,opt,name=Green,proto3" json:"Green,omitempty"`
	Blue  int32   `protobuf:"varint,3,opt,name=Blue,proto3" json:"Blue,omitempty"`
	LEDs  []int32 `protobuf:"varint,4,rep,packed,name=LEDs,proto3" json:"LEDs,omitempty"`
}

func (x *SetLEDRequest) Reset() {
	*x = SetLEDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blinky_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetLEDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLEDRequest) ProtoMessage() {}

func (x *SetLEDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blinky_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLEDRequest.ProtoReflect.Descriptor instead.
func (*SetLEDRequest) Descriptor() ([]byte, []int) {
	return file_blinky_proto_rawDescGZIP(), []int{0}
}

func (x *SetLEDRequest) GetRed() int32 {
	if x != nil {
		return x.Red
	}
	return 0
}

func (x *SetLEDRequest) GetGreen() int32 {
	if x != nil {
		return x.Green
	}
	return 0
}

func (x *SetLEDRequest) GetBlue() int32 {
	if x != nil {
		return x.Blue
	}
	return 0
}

func (x *SetLEDRequest) GetLEDs() []int32 {
	if x != nil {
		return x.LEDs
	}
	return nil
}

type SetLEDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LEDs []int32 `protobuf:"varint,4,rep,packed,name=LEDs,proto3" json:"LEDs,omitempty"`
}

func (x *SetLEDResponse) Reset() {
	*x = SetLEDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blinky_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetLEDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLEDResponse) ProtoMessage() {}

func (x *SetLEDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blinky_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLEDResponse.ProtoReflect.Descriptor instead.
func (*SetLEDResponse) Descriptor() ([]byte, []int) {
	return file_blinky_proto_rawDescGZIP(), []int{1}
}

func (x *SetLEDResponse) GetLEDs() []int32 {
	if x != nil {
		return x.LEDs
	}
	return nil
}

type GetLEDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LEDs []int32 `protobuf:"varint,1,rep,packed,name=LEDs,proto3" json:"LEDs,omitempty"`
}

func (x *GetLEDRequest) Reset() {
	*x = GetLEDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blinky_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLEDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLEDRequest) ProtoMessage() {}

func (x *GetLEDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blinky_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLEDRequest.ProtoReflect.Descriptor instead.
func (*GetLEDRequest) Descriptor() ([]byte, []int) {
	return file_blinky_proto_rawDescGZIP(), []int{2}
}

func (x *GetLEDRequest) GetLEDs() []int32 {
	if x != nil {
		return x.LEDs
	}
	return nil
}

type LEDStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LED   int32 `protobuf:"varint,1,opt,name=LED,proto3" json:"LED,omitempty"`
	Red   int32 `protobuf:"varint,2,opt,name=Red,proto3" json:"Red,omitempty"`
	Green int32 `protobuf:"varint,3,opt,name=Green,proto3" json:"Green,omitempty"`
	Blue  int32 `protobuf:"varint,4,opt,name=Blue,proto3" json:"Blue,omitempty"`
}

func (x *LEDStatus) Reset() {
	*x = LEDStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blinky_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LEDStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LEDStatus) ProtoMessage() {}

func (x *LEDStatus) ProtoReflect() protoreflect.Message {
	mi := &file_blinky_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LEDStatus.ProtoReflect.Descriptor instead.
func (*LEDStatus) Descriptor() ([]byte, []int) {
	return file_blinky_proto_rawDescGZIP(), []int{3}
}

func (x *LEDStatus) GetLED() int32 {
	if x != nil {
		return x.LED
	}
	return 0
}

func (x *LEDStatus) GetRed() int32 {
	if x != nil {
		return x.Red
	}
	return 0
}

func (x *LEDStatus) GetGreen() int32 {
	if x != nil {
		return x.Green
	}
	return 0
}

func (x *LEDStatus) GetBlue() int32 {
	if x != nil {
		return x.Blue
	}
	return 0
}

type GetLEDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status []*LEDStatus `protobuf:"bytes,1,rep,name=Status,proto3" json:"Status,omitempty"`
}

func (x *GetLEDResponse) Reset() {
	*x = GetLEDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blinky_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLEDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLEDResponse) ProtoMessage() {}

func (x *GetLEDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blinky_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLEDResponse.ProtoReflect.Descriptor instead.
func (*GetLEDResponse) Descriptor() ([]byte, []int) {
	return file_blinky_proto_rawDescGZIP(), []int{4}
}

func (x *GetLEDResponse) GetStatus() []*LEDStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_blinky_proto protoreflect.FileDescriptor

var file_blinky_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x62, 0x6c, 0x69, 0x6e, 0x6b, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x62, 0x6c, 0x69, 0x6e, 0x6b, 0x79, 0x22, 0x5f, 0x0a, 0x0d, 0x53, 0x65, 0x74, 0x4c, 0x45, 0x44,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x52, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x47, 0x72, 0x65,
	0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x47, 0x72, 0x65, 0x65, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x42, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x42,
	0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4c, 0x45, 0x44, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x05, 0x52, 0x04, 0x4c, 0x45, 0x44, 0x73, 0x22, 0x24, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x4c, 0x45,
	0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4c, 0x45, 0x44,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x4c, 0x45, 0x44, 0x73, 0x22, 0x23, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x4c, 0x45, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x4c, 0x45, 0x44, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x4c, 0x45,
	0x44, 0x73, 0x22, 0x59, 0x0a, 0x09, 0x4c, 0x45, 0x44, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x10, 0x0a, 0x03, 0x4c, 0x45, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x4c, 0x45,
	0x44, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x52, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x47, 0x72, 0x65, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x47, 0x72, 0x65, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x42, 0x6c, 0x75,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x42, 0x6c, 0x75, 0x65, 0x22, 0x3b, 0x0a,
	0x0e, 0x47, 0x65, 0x74, 0x4c, 0x45, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x29, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x62, 0x6c, 0x69, 0x6e, 0x6b, 0x79, 0x2e, 0x4c, 0x45, 0x44, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x80, 0x01, 0x0a, 0x06, 0x42,
	0x6c, 0x69, 0x6e, 0x6b, 0x79, 0x12, 0x3a, 0x0a, 0x07, 0x53, 0x65, 0x74, 0x4c, 0x45, 0x44, 0x73,
	0x12, 0x15, 0x2e, 0x62, 0x6c, 0x69, 0x6e, 0x6b, 0x79, 0x2e, 0x53, 0x65, 0x74, 0x4c, 0x45, 0x44,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x62, 0x6c, 0x69, 0x6e, 0x6b, 0x79,
	0x2e, 0x53, 0x65, 0x74, 0x4c, 0x45, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x3a, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4c, 0x45, 0x44, 0x73, 0x12, 0x15, 0x2e, 0x62,
	0x6c, 0x69, 0x6e, 0x6b, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x45, 0x44, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x62, 0x6c, 0x69, 0x6e, 0x6b, 0x79, 0x2e, 0x47, 0x65, 0x74,
	0x4c, 0x45, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2c, 0x5a,
	0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x61, 0x74, 0x69,
	0x6e, 0x65, 0x2f, 0x62, 0x6c, 0x69, 0x6e, 0x6b, 0x79, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_blinky_proto_rawDescOnce sync.Once
	file_blinky_proto_rawDescData = file_blinky_proto_rawDesc
)

func file_blinky_proto_rawDescGZIP() []byte {
	file_blinky_proto_rawDescOnce.Do(func() {
		file_blinky_proto_rawDescData = protoimpl.X.CompressGZIP(file_blinky_proto_rawDescData)
	})
	return file_blinky_proto_rawDescData
}

var file_blinky_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_blinky_proto_goTypes = []interface{}{
	(*SetLEDRequest)(nil),  // 0: blinky.SetLEDRequest
	(*SetLEDResponse)(nil), // 1: blinky.SetLEDResponse
	(*GetLEDRequest)(nil),  // 2: blinky.GetLEDRequest
	(*LEDStatus)(nil),      // 3: blinky.LEDStatus
	(*GetLEDResponse)(nil), // 4: blinky.GetLEDResponse
}
var file_blinky_proto_depIdxs = []int32{
	3, // 0: blinky.GetLEDResponse.Status:type_name -> blinky.LEDStatus
	0, // 1: blinky.Blinky.SetLEDs:input_type -> blinky.SetLEDRequest
	2, // 2: blinky.Blinky.GetLEDs:input_type -> blinky.GetLEDRequest
	1, // 3: blinky.Blinky.SetLEDs:output_type -> blinky.SetLEDResponse
	4, // 4: blinky.Blinky.GetLEDs:output_type -> blinky.GetLEDResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_blinky_proto_init() }
func file_blinky_proto_init() {
	if File_blinky_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_blinky_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetLEDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blinky_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetLEDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blinky_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLEDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blinky_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LEDStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blinky_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLEDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_blinky_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blinky_proto_goTypes,
		DependencyIndexes: file_blinky_proto_depIdxs,
		MessageInfos:      file_blinky_proto_msgTypes,
	}.Build()
	File_blinky_proto = out.File
	file_blinky_proto_rawDesc = nil
	file_blinky_proto_goTypes = nil
	file_blinky_proto_depIdxs = nil
}
